//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitProjectAssignment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MitDatabaseEntities1 : DbContext
    {
        public MitDatabaseEntities1()
            : base("name=MitDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Countrie> Countrie { get; set; }
        public virtual DbSet<Downloads> Downloads { get; set; }
        public virtual DbSet<NoteCategories> NoteCategories { get; set; }
        public virtual DbSet<NoteTypes> NoteTypes { get; set; }
        public virtual DbSet<ReferenceData> ReferenceData { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<SellerNotes> SellerNotes { get; set; }
        public virtual DbSet<SellerNotesAttachments> SellerNotesAttachments { get; set; }
        public virtual DbSet<SellerNotesReportedIssues> SellerNotesReportedIssues { get; set; }
        public virtual DbSet<SellerNotesReviews> SellerNotesReviews { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<SystemConfigurations> SystemConfigurations { get; set; }
    }
}
