//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitProjectAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerNotesReportedIssues
    {
        public int ID { get; set; }
        public int NoteID { get; set; }
        public int ReportedBYID { get; set; }
        public int AgainstDownloadID { get; set; }
        public string Remarks { get; set; }
    
        public virtual Downloads Downloads { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual Registration Registration1 { get; set; }
    }
}
